version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Specify the Python version
    commands:
      - echo Installing dependencies
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Setting environment variables
      - export FLASK_APP=app.py
      - export FLASK_ENV=production
      - export SECRET_KEY=${SECRET_KEY}  # Replace with your actual secret key environment variable

  build:
    commands:
      - echo Starting Flask application
      - python -m flask run

artifacts:
  files:
    - '**/*'
    - '!**/tests/**'  # Exclude test files
  discard-paths: no

environment:
  variables:
    SECRET_KEY: ${SECRET_KEY}  # Replace with an actual value or set in CodeBuild environment
